### ISSUE TITLE
Auth0 Callback URL mismatch for https://signsfive-web-staging.herokuapp.com

### ISSUE THREAD

**Issue by meltedspork** [deafchi/signsfive-web#34]
after trying to logging in Auth0 it appears that we got mismatch callback error.

<img width="817" alt="mismatch-staging-url-callback" src="https://user-images.githubusercontent.com/2738505/35664713-cce18746-06e8-11e8-805f-f31fdced8eb4.png">

**Comment by kratsg** [comment]
Updated. Please check again.

**Comment by meltedspork** [comment]
IT WORKS! Thanks!  👍
